version: "3.8"

services:
  msvc-users:
    build:
      context: ./msvc-users
      dockerfile: Dockerfile
    command: mvn package install -DskipTests --also-make --threads=2 && mvn spring-boot:run
    ports:
      - "8009:8009"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres?searchPath=inn
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - my-network
  msvc-payments:
    build:
      context: ./msvc-payments
      dockerfile: Dockerfile
    command: mvn package install -DskipTests --also-make --threads=2 && mvn spring-boot:run
    ports:
      - "8008:8008"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres?searchPath=inn
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - my-network

  msvc-products:
    build:
      context: ./msvc-products
      dockerfile: Dockerfile
    command: mvn package install -DskipTests --also-make --threads=2 && mvn spring-boot:run
    ports:
      - "8006:8006"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres?searchPath=inn
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - my-network

  msvc-orders:
    build:
      context: ./msvc-orders
      dockerfile: Dockerfile
    command: mvn package install -DskipTests --also-make --threads=2 && mvn spring-boot:run
    ports:
      - "8007:8007"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres?searchPath=inn
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - my-network

  msvc-gateway-server:
    build:
      context: ./msvc-gateway-server
      dockerfile: Dockerfile
    command: mvn package install -DskipTests --also-make --threads=2 && mvn spring-boot:run
    ports:
      - "8086:8086"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED=true
      - SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_PREDICATE_PATH=/service/**
    depends_on:
      - eureka-server
    networks:
      - my-network

  msvc-entities:
    build:
      context: ./msvc-entities
      dockerfile: Dockerfile
    command: mvn package install -DskipTests --also-make --threads=2 && mvn spring-boot:run
    ports:
      - "8003:8003"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres?searchPath=inn
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - my-network

  msvc-address:
    build:
      context: ./msvc-address
      dockerfile: Dockerfile
    command: mvn package install -DskipTests --also-make --threads=2 && mvn spring-boot:run
    ports:
      - "8002:8002"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres?searchPath=inn
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - my-network

  eureka-server:
    build:
      context: ./msvc-eureka-server
      dockerfile: Dockerfile
    command: mvn package install -DskipTests --also-make --threads=2 && mvn spring-boot:run
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - my-network

  warehouse-service:
    build:
      context: ./msvc-warehouses
      dockerfile: Dockerfile
    command: mvn package install -DskipTests --also-make --threads=2 && mvn spring-boot:run
    ports:
      - "8004:8004"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - my-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432" # Cambiar el puerto de enlace a 5433
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
