eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: msvc-products
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
