eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka}
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP:false}

spring:
  application:
    name: msvc-orders
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true