server:
  port: 8009

spring:
  application:
    name: msvc-users
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/system_users
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: postgres
      mode: always
  security:
    oauth2:
      authorization:
        server:
          issuer: http://localhost:8009