resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-duration-threshold: 3s
        slow-call-rate-threshold: 50
    instances:
      products:
        base-config: defecto
  timelimiter:
    configs:
      defecto:
        timeout-duration: 3s
    instances:
      products:
        base-config: defecto
        
spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://127.0.0.1:9100
#      client:
#        registration:
#          client-app:
#            provider: spring
#            client-id: gateway-app
#            client-secret: 12345
#            authorization-grant-type: authorization_code
#            redirect-uri: http://127.0.0.1:8090/authorized
#            scope:
#            - openid
#            - profile
#            client-name: client-app
#        provider:
#          spring:
#            issuer-uri: http://127.0.0.1:9100
  cloud:
    gateway:
      routes:
#      - id: msvc-oauth
#        uri: lb://msvc-oauth
#        predicates:
#        - Path=/**
      - id: msvc-users
        uri: lb://msvc-users
        predicates:
        - Path=/api/users/**
      - id: msvc-warehouses
        uri: lb://msvc-warehouses
        predicates:
        - Path=/api/warehouses/**
      - id: msvc-products
        uri: lb://msvc-products
        predicates:
        - Path=/api/products/**
      - id: msvc-address
        uri: lb://msvc-address
        predicates:
        - Path=/api/addresses/**
      - id: msvc-payments
        uri: lb://msvc-payments
        predicates:
        - Path=/api/payments/**
      - id: msvc-entities
        uri: lb://msvc-entities
        predicates:
        - Path=/api/entities/**
      - id: msvc-orders
        uri: lb://msvc-orders
        predicates:
        - Path=/api/orders/**