resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-duration-threshold: 3s
        slow-call-rate-threshold: 50
    instances:
      products:
        base-config: defecto
  timelimiter:
    configs:
      defecto:
        timeout-duration: 3s
    instances:
      products:
        base-config: defecto
        
spring:
  cloud:
    gateway:
      routes:
      - id: msvc-users
        uri: lb://msvc-users
        predicates:
        - Path=/api/users/**
      - id: msvc-warehouses
        uri: lb://msvc-warehouses
        predicates:
        - Path=/api/warehouses/**
        filters:
           - AuthenticationFilter
      - id: msvc-products
        uri: lb://msvc-products
        predicates:
        - Path=/api/products/**
        filters:
           - AuthenticationFilter
      - id: msvc-address
        uri: lb://msvc-address
        predicates:
        - Path=/api/addresses/**
        filters:
           - AuthenticationFilter
      - id: msvc-payments
        uri: lb://msvc-payments
        predicates:
        - Path=/api/payments/**
        filters:
           - AuthenticationFilter
      - id: msvc-entities
        uri: lb://msvc-entities
        predicates:
        - Path=/api/entities/**
        filters:
           - AuthenticationFilter
      - id: msvc-orders
        uri: lb://msvc-orders
        predicates:
        - Path=/api/orders/**
        filters:
           - AuthenticationFilter